config/routes.rb
MusicCatalog::Application.routes.draw do
  root to: 'bands#index'
  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
  	resources :albums, only: :new
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
  	resources :tracks, only: :new
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to(
    :user
  )

  belongs_to(
    :track
  )
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action(only: :destroy) do
    @note = Note.find(params[:id])
    unless @note.user == current_user
      render text: "Status 404 - Forbidden", status: :forbidden
    end
  end

  def create
    @note = current_user.notes.new(note_params)
    @note.track_id = params[:track_id]

    current_user.save
    redirect_to track_url(@note.track)
  end

  def update
    render json: "Updating"
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy!
    redirect_to track_url(@note.track)
  end

  private
  def note_params
    params.require(:note).permit(:text)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<h4>Add Notes to this track</h4>

<form action="<%= track_notes_url(@track) %>" method="POST">
  <textarea name="note[text]"><%= @note.text %></textarea>
  <%= render "shared/form_auth" %>
  <input type="submit" value="Submit note">
</form>
<br>

app/views/notes/_note.html.erb
<% if @track.notes.count > 0 %>
  <table>
    <tr>
      <td><big><strong>User</strong></big></td>
      <td><big><strong>Comment</strong></big></td>
    </tr>
  <% @track.notes.each do |note| %>
    <tr>
      <td><%= note.user.email %></td>
      <td><%= note.text %> </td>
      <td>
        <% if note.user == current_user %>
          <form action="<%= track_note_url(@track, note) %>" method="POST">
            <%= render "shared/form_auth" %>
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Delete">
          </form>
        <% end %>

      </td>
    </tr>
    <br>
  <% end %>
<% end %>