config/routes.rb
MusicCatalog::Application.routes.draw do
  root to: 'bands#index'
  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
  	resources :albums, only: :new
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
  	resources :tracks, only: :new
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, presence: true

  belongs_to(
    :album,
    inverse_of: :tracks
  )

  has_one(
    :band,
    through: :album,
    source: :band
  )

  has_many(
    :notes
  )
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action do
    unless logged_in?
      flash[:errors] = ["Please log in first"]
      redirect_to new_session_url
    end
  end

  def show
    @track = Track.find(params[:id])
    @note = Note.new
    render :show
  end

  def new
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)
    @track.album = Album.find(params[:track][:album_id])

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end


  def edit
    @track = Track.find(params[:id])
    render :edit
  end


  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy!
    redirect_to album_url(@track.album)
  end

private
  def track_params
    params.require(:track).permit(:name, :lyrics)

  end
end

app/helpers/tracks_helper.rb
module TracksHelper
	def ugly_lyrics(lyrics)
		lyrics = lyrics.split("\n")

		ugly_lyrics = ""
		lyrics.each do |line|
			if line == "\r"
				ugly_lyrics += "\r\n"
			else
				ugly_lyrics += "♫ " + h(line) + "\n" 
			end
		end

		"<pre>#{ugly_lyrics.html_safe}</pre>".html_safe
	end
end

app/views/tracks/edit.html.erb
<!-- Track Edit Page -->

<form action="<%= track_url(@track) %>" method="POST">
  <%= render "shared/form_auth" %>

  <input type="hidden" name="_method" value="PUT">

  <label for="track_name">Track Name</label>
  <input type="text"
         name="track[name]"
         value="<%= @track.name %>"
         id="track_name">
   <br>

   <label for="track_lyrics">Lyrics</label>
   <br>
   <textarea id="track_lyrics" name="track[lyrics]"><%= @track.lyrics %></textarea>
   <br>
  <input type="submit" value="Complete edit">
</form>

app/views/tracks/new.html.erb
<h1>Submit a new track</h1>

<form action="<%= tracks_url %>" method="POST">
  <%= render "shared/form_auth" %>

  <label for="track_album_id">Album</label>
  <select name="track[album_id]">
    <% Album.all.each do |album| %>
      <option value=<%= album.id %>
        <%= "selected=selected".html_safe if @track.album == album %>>
        <%= album.name %>
      </option>
    <% end %>
  </select>

  <br>
  <label for="track_name">Track Name</label>
  <input type="text" name="track[name]" id="track_name">
  <br>

  <input type="submit" value="Submit Track">
</form>

app/views/tracks/show.html.erb
<!-- Track Show Page -->

<h1>
  <a href="<%= band_url(@track.band) %>">
    <%= @track.band.name %>
  </a>
</h1>
<h2>
  <a href="<%= album_url(@track.album) %>">
    <%= @track.album.name %>
  </a></h2>

<h3><%= @track.name %></h3>

<p>
<h4>Song Lyrics</h4>
<%= ugly_lyrics(@track.lyrics) %>
</p>
<br>

  <form action="<%= track_url(@track) %>" method="POST">
    <%= render "shared/form_auth" %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this track">
  </form>

<small>
  <a href ="<%= edit_track_url(@track) %>">
    Edit this track
  </a>
</small>


<%= render "notes/form" %>
<%= render "notes/note" %>

<p>
</p>