config/routes.rb
MusicCatalog::Application.routes.draw do
  root to: 'bands#index'
  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
  	resources :albums, only: :new
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
  	resources :tracks, only: :new
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, presence: true
  belongs_to(
    :band,
    inverse_of: :albums
  )

  has_many(
    :tracks,
    inverse_of: :album,
    dependent: :destroy
  )
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action do
    unless logged_in?
      flash[:errors] = ["Please log in first"]
      redirect_to new_session_url
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to band_url(@album.band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end


  def edit
    @album = Album.find(params[:id])
    render :edit
  end


  def update
    @album = Album.find(params[:id])
    @album.band_id = params[:band_id]
    @album.recording_style = params[:album][:recording_style]

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.error.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy!
    redirect_to band_url(@album.band)
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :recording_style)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<!--Album Edit Page -->

<form action="<%= album_url(@album) %>" method="POST">
  <%= render "shared/form_auth" %>

  <input type="hidden" name="_method" value="PUT">

  <label for="album_band_id">Band</label>
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value=<%= band.id %>
       <% if @album.band.id == band.id %>

          <%= "selected=selected".html_safe %>
        <% end %>>
        <%= band.name %>
      </option>
    <% end %>
  </select>

  <label for="album_name">Album Name</label>
  <input type="text"
         name="album[name]"
         id="album_name"
         value="<%= @album.name %>">

<br>
  <label for="album_recording_style">Album Style</label>
  <input type="radio"
    name="album[recording_style]"
    id="album_recording_style"
    value="live"
    <% if @album.recording_style == "Live" %>
      checked="checked"
    <% end %>>
      Live
  </option>

  <input type="radio"
    name="album[recording_style]"
    id="album_recording_style"
    value="studio"
    <% if @album.recording_style == "Studio" %>
      checked="checked"
    <% end %>>
    Studio
  </option>

  <br>
  <input type="submit" value="Complete Edit">
</form>

app/views/albums/new.html.erb
<h1>Submit a new album</h1>

<form action="<%= albums_url %>" method="POST">
  <%= render "shared/form_auth" %>

  <label for="album_band_id">Band</label>
  <select name="album[band_id]">

    <% Band.all.each do |band| %>
      <option value=<%= band.id %>

        <% if @album.band.id == band.id %>
          <%= "selected=selected" %>
        <% end %>>
        <%= band.name %>
      </option>
    <% end %>
  </select>
<br>
    <label for="album_name">Album Name</label>
    <input type="text"
           name="album[name]"
           id="album_name"
           value="<%= @album.name %>">

  <br>
    <label for="album_recording_style">Album Style</label>
    <input type="radio"
      name="album[recording_style]"
      id="album_recording_style"
      value="live"
      <% if @album.recording_style == "Live" %>
        checked="checked"
      <% end %>>
        Live
    </option>

    <input type="radio"
      name="album[recording_style]"
      id="album_recording_style"
      value="studio"
      <% if @album.recording_style == "Studio" %>
        checked="checked"
      <% end %>>
      Studio
    </option>

    <br>
    <input type="submit" value="Submit Album">
</form>

app/views/albums/show.html.erb
<!-- Album Show Page -->

<h1><a href="<%= band_url(@album.band) %>">
    <%= @album.band.name %>
  </a>
</h1>

<h2><%= @album.name %></h2>

<a href="<%= new_album_track_url(@album) %>">Add a new track!</a>
<br>
<br>

<p>
  <form action="<%= album_url(@album) %>" method="POST">
    <%= render "shared/form_auth" %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this album">
  </form>
  <small>
  <a href="<%= edit_album_url(@album) %>">
    Edit this album
  </a>
</small>
</p>
<br>
<br>

  <% @album.tracks.each do |track| %>
    <a href="<%= track_url(track) %>">
     <%=  track.name %>
    </a>
    <br>
  <% end %>