config/routes.rb
MusicCatalog::Application.routes.draw do
  root to: 'bands#index'
  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
  	resources :albums, only: :new
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
  	resources :tracks, only: :new
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many(
    :albums,
    inverse_of: :band,
    dependent: :destroy
 )

 has_many(
   :tracks,
   through: :albums,
   source: :tracks
 )
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action do
    unless logged_in?
      flash[:errors] = ["Please log in first"]
      redirect_to new_session_url
    end
  end

  def index
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end


  def edit
    @band = Band.find(params[:id])
    render :edit
  end


  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])

    if @band.destroy
      flash[:errors] = ["#{@band.name} deleted!"]
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/edit.html.erb
<!-- Band Edit Page -->

<form action="<%= band_url(@band) %>" method="POST">
  <%= render "shared/form_auth" %>

  <input type="hidden" name="_method" value="PUT">

  <label for="band_name">Band Name</label>
  <input type="text"
         name="band[name]"
         value="<%= @band.name %>"
         id="band_name">
   <br>

  <input type="submit" value="Complete edit">
</form>

app/views/bands/index.html.erb
<h1>All Bands!</h1>
<table>
  <% Band.all.each do |band| %>
    <tr><td>
          <a href="<%= band_url(band) %>"><%= band.name %></a>
        </td>
        <td>
          <%= band.albums.count %> Album<%= "s" if band.albums.count > 1 %>
        </td>
    </tr>
  <% end %>
</table>

<br>
<a href="<%= new_band_url %>">Submit a new band!</a>

app/views/bands/new.html.erb
<h1>Submit a new band!</h1>

<form action="<%= bands_url %>" method="POST">
  <%= render "shared/form_auth" %>

  <label for="band_name">Band Name</label>
  <input type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit" value="Submit Band">
</form>

app/views/bands/show.html.erb
<!-- Band Show page -->

<h1><%= @band.name %></h1>

<a href="<%= new_band_album_url(@band) %>">Add a new album!</a>
<br>
<br>

<p>
  <% @band.albums.each do |album| %>
  <table>
    <tr><td>
          <a href="<%= album_url(album) %>">
            <big><%= album.name %></big>
          </a>
        </td>
        <td>
          <% if album.recording_style %>
            (<%= album.recording_style.capitalize %>)
          <% end %>
        </td>
    </tr>
  </table>

  <% if album.tracks.count == 0 %>
    <ul><li>No tracks</li></ul>
  <% else %>
    <ul>
      <% album.tracks.each do |track| %>
        <tr><td>
              <li>
                <a href="<%= track_url(track) %>"><%=  track.name %></a>
              </li>
            </td>
        </tr>
      <% end %>
    </ul>
  <% end %>
  </p>
<% end %>

<small>
  <a href="<%= edit_band_url(@band) %>">
    Edit this band
  </a>
  <form action="<%= band_url(@band) %>" method="POST">
    <%= render "shared/form_auth" %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this band">
  </form>
</small>